# Generated by Django 4.2.4 on 2023-08-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataextractor', '0002_feedback_date_feedback_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
